apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:

      # ── 1. Prometheus  ──
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      # ── 2. Node Exporter ──
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ['monitoring']
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: node-exporter

      # ── 3. kube-state-metrics ──
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']

      # ── 4. Postgres exporter ──
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter-svc.inventory.svc.cluster.local:9187']

      # ── 5. Redis exporter ──
      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter-svc.inventory.svc.cluster.local:9121']

      # ── 6. Inventory App  ──
      - job_name: 'inventory-app'
        metrics_path: '/api/v1/metrics'
        static_configs:
          - targets: ['app-svc.inventory.svc.cluster.local:3000']