apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec: 
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      automountServiceAccountToken: false
      
      hostNetwork: true

      tolerations:
        - operator: Exists        # run on ALL nodes including control plane

      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.7.0
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
            - "--path.rootfs=/host"
            - "--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker)($|/)"
          ports:
            - containerPort: 9100
              hostPort: 9100

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
              ephemeral-storage: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "256Mi"

          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host
              readOnly: true

      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  clusterIP: None
  selector:
    app: node-exporter
  ports:
    - port: 9100
      targetPort: 9100