apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter-deployment
  namespace: inventory-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template: 
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.62.0

          ports:
            - containerPort: 9121
              name: metrics

          env:
            - name: REDIS_ADDR
              value: "redis://redis-service:6379"

          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"

          readinessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /metrics
              port: 9121
            initialDelaySeconds: 15
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter-svc
  namespace: inventory
  labels:
    app: redis-exporter
spec:
  type: ClusterIP
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics