apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: inventory-prod
spec:
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  replicas: 1

  template:
    metadata:
      labels:
        app: redis

    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:6-alpine
          command:
            - sh
            - -c
            - 'redis-server --requirepass "$REDIS_PASSWORD"'
          ports:
            - containerPort: 6379
              name: redis

          volumeMounts:
            - name: redis-pvc
              mountPath: /data

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"
            requests:
              memory: "256Mi"
              cpu: "250m"  
              ephemeral-storage: "1Gi"
                  

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" ping'
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - 'redis-cli -a "$REDIS_PASSWORD" ping'
            initialDelaySeconds: 10
            periodSeconds: 5

          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis-service

  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi