apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit-deployment
  namespace: inventory-dev
spec:
  automountServiceAccountToken: false
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      containers:
      - name: mailpit
        image: axllent/mailpit:v1.31.0

        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          requests:
            memory: "128Mi"
            cpu: "100m"
            ephemeral-storage: "512Mi"

        ports:
          - containerPort: 1025  
            name: smtp
          - containerPort: 8025  
            name: web-ui

---
apiVersion: v1
kind: Service
metadata:
  name: mailpit-service
  labels:
    app: mailpit
  namespace: inventory-dev  
spec:
  type: ClusterIP
  selector:
    app: mailpit
  ports:
  - port: 8025
    targetPort: 8025
    name: web-ui
  - port: 1025
    targetPort: 1025
    name: smtp  
