apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-worker
  namespace: inventory-prod
  labels:
    app: inventory-worker

spec:
  replicas: 2

  selector:
    matchLabels:
      app: inventory-worker

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: inventory-worker

    spec:
      serviceAccountName: inventory-app-sa

      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-svc -U admin -d inventory_app;
              do echo "Waiting for postgres..."; sleep 2; done
              echo "Postgres is ready!"

        - name: wait-for-redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - |
              until redis-cli -h redis-service -p 6379 ping;
              do echo "Waiting for redis..."; sleep 2; done
              echo "Redis is ready!"

      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001

      containers:
        - name: inventory-worker
          image: ayaelalfy/inventory_app:73
          imagePullPolicy: Always

          command: ["node", "dist/main.js"]

          env:
            - name: START_MODE
              value: "worker"

          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

          volumeMounts:
            - name: tmp
              mountPath: /app/tmp

          livenessProbe:
            exec:
              command:
                - node
                - -e
                - "process.exit(0)"
            initialDelaySeconds: 20
            periodSeconds: 30
            failureThreshold: 3

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault

      volumes:
        - name: tmp
          emptyDir: {}