apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-app-sa
  namespace: inventory-prod
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: inventory-app-role
  namespace: inventory-prod
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: inventory-app-rolebinding
  namespace: inventory-prod
subjects:
  - kind: ServiceAccount
    name: inventory-app-sa
    namespace: inventory-prod
roleRef:
  kind: Role
  name: inventory-app-role
  apiGroup: rbac.authorization.k8s.io
