pipeline {
    agent { label "agent3" }
    
    environment {
        APP_NAME        = "inventory_app"
        IMAGE_TAG       = "${BUILD_NUMBER}"
        REGISTRY        = "ayaelalfy"
        SONAR_HOST_URL  = "http://172.17.0.1:9000"
        SONAR_PROJECT_KEY = "inventory_app"
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning the repository...'
                checkout scm
            }
        }
        
       stage('🔎 SonarQube Analysis') {
           steps {
             withSonarQubeEnv('SonarQube') {
              sh '''
                rm -rf .scannerwork

                sonar-scanner \
                  -Dsonar.projectKey=inventory_app \
                  -Dsonar.sources=. \
                  -Dsonar.host.url=$SONAR_HOST_URL \
                  -Dsonar.login=$SONAR_TOKEN
            '''
                  }
              }
         }
         
        stage('🚦 Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        
        stage('🐳 Build Docker Image') {
            steps {
                sh "docker build -t ${REGISTRY}/${APP_NAME}:${IMAGE_TAG} ."
            }
        }
        
        stage('📦 Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${REGISTRY}/${APP_NAME}:${IMAGE_TAG}
                        docker logout
                    '''
                }
            }
        }
    }
    
    post {
        success {
            echo '✅ CI done! ArgoCD will deploy automatically.'
        }
        failure {
            echo '❌ Pipeline failed!'
        }
        always {
            cleanWs()
        }
    }
}