pipeline {
    agent { label "agent3" }

    environment {
        APP_NAME          = "inventory_app"
        IMAGE_TAG         = "${BUILD_NUMBER}"
        REGISTRY          = "ayaelalfy"
        SONAR_HOST_URL    = "http://172.17.0.1:9000"
        SONAR_PROJECT_KEY = "inventory_app"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    withCredentials([string(
                        credentialsId: 'jenkins-sonar',
                        variable: 'SONAR_TOKEN'
                    )]) {
                        sh """
                            /opt/sonar-scanner/bin/sonar-scanner \
                                -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                                -Dsonar.sources=. \
                                -Dsonar.host.url=${SONAR_HOST_URL} \
                                -Dsonar.token=\${SONAR_TOKEN}
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${REGISTRY}/${APP_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh """
                    trivy image \
                        --severity LOW,MEDIUM,HIGH \
                        --exit-code 0 \
                        --quiet \
                        --format json \
                        -o trivy-medium.json \
                        ${REGISTRY}/${APP_NAME}:${IMAGE_TAG}

                    trivy image \
                        --severity CRITICAL \
                        --exit-code 0 \
                        --quiet \
                        --format json \
                        -o trivy-critical.json \
                        ${REGISTRY}/${APP_NAME}:${IMAGE_TAG}
                """
            }
            post {
                always {
                    archiveArtifacts artifacts: 'trivy-*.json', fingerprint: true
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh """
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push ${REGISTRY}/${APP_NAME}:${IMAGE_TAG}
                        docker logout
                    """
                }
            }
        }

        stage('Update Infra (GitOps)') {
            steps {
                echo 'Updating image tag in Kubernetes manifests...'
                withCredentials([string(                        
                    credentialsId: 'jenkins-github',
                    variable: 'GIT_TOKEN'
                )]) {
                    sh """
                        rm -rf inventory_app
                        git clone https://$GIT_TOKEN@github.com/ayaelalfy-CSAI/inventory_app.git
                        cd inventory_app
                      
                        sed -i 's|image: ${REGISTRY}/${APP_NAME}:.*|image: ${REGISTRY}/${APP_NAME}:${IMAGE_TAG}|g' k8s/deployments/app.yml
                        git config user.email "jenkins@ci.com"
                        git config user.name "Jenkins CI"
                        git add k8s/deployments/app.yml
                        git commit -m "CI: update image tag to ${IMAGE_TAG}"
                        git push origin master
                    """
                    
                }
            }
        }
    }

    post {                                                     
        success {
            echo 'CI done! ArgoCD will deploy automatically.'
        }
        failure {
            echo 'Pipeline failed!ckeck the logs for more details.'
        }
        always {
            cleanWs()
        }
    }
}
