apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-app
  namespace: monitoring
data:
  app-rules.yml: |
    groups:
      - name: inventory-app-alerts
        rules:
          - alert: AppDown
            expr: up{job="inventory-app"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Inventory app is down"
              description: "The inventory-app target has been unreachable for more than 1 minute."

          - alert: HighErrorRate
            expr: rate(inventory_app_http_requests_total{status_code=~"5.."}[5m]) > 0.05
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High 5xx error rate on inventory-app"
              description: "More than 5% of requests are failing with 5xx errors over the last 5 minutes."

          - alert: HighMemoryUsage
            expr: (container_memory_usage_bytes{namespace="inventory-prod"} / container_spec_memory_limit_bytes{namespace="inventory"}) > 0.9
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Container memory usage above 90%"
              description: "{{ $labels.pod }} is using more than 90% of its memory limit."