apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
  namespace: inventory-prod 
spec:
  serviceName: postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1

  template:
    metadata:
      labels:
        app: postgres

    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432
              name: postgres

          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data

          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
              ephemeral-storage: "2Gi"    
            requests:
              memory: "256Mi"
              cpu: "250m" 
              ephemeral-storage: "1Gi"
                   

          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
                - -d
                - inventory_app
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          envFrom:
            - secretRef:
                name: postgres-secret

  volumeClaimTemplates:
    - metadata:
        name: postgres-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 4Gi