apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulset
  namespace: inventory
spec:
  serviceName: redis-service
  selector:
    matchLabels:
      app: redis
  replicas: 1

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:6-alpine
          command: ["redis-server"]
          ports:
            - containerPort: 6379
              name: redis

          volumeMounts:
            - name: redis-pvc
              mountPath: /data

          
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - redis-cli ping
            initialDelaySeconds: 10
            periodSeconds: 5

          
          env:
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis-service
                      
  volumeClaimTemplates:
    - metadata:
        name: redis-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi